#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

ddev typo3 setup \
        --driver=mysqli \
        --host=db \
        --port=3306 \
        --dbname=db \
        --username=db \
        --password=db \
        --admin-username=admin \
        --admin-user-password='Password_!23' \
        --admin-email="john.doe@example.com" \
        --no-interaction \
        --server-type=apache \
        --force
ddev import-db --file=.project/data/db.sql.gz
#mkdir -p config/sites/main && cp config/sites/config.yaml config/sites/main/
#ddev typo3 install:setup
ddev typo3 extension:setup
mkdir -p .Build/public/fileadmin
git restore config/system/settings.php
#cd .Build/public/ && tar xf ../../.project/data/fileadmin.tar.gz
